# Generated by Django 4.1 on 2022-08-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='امتیاز'),
        ),
    ]
