# Generated by Django 4.1 on 2022-08-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_alter_food_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('S', 'صبحانه'), ('N', 'تهار'), ('SH', 'شام'), ('D', 'نوشیدنی')], default='D', max_length=10, verbose_name='نوع'),
        ),
    ]
