# Generated by Django 4.1 on 2022-08-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_alter_food_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('lunch', 'تهار'), ('dinner', 'شام'), ('drinks', 'نوشیدنی')], default='drinks', max_length=10, verbose_name='نوع'),
        ),
    ]
